### ISSUE TITLE
Release new version for PreUpdate fix

### ISSUE THREAD

**Issue by robo-corg** [aevyrie/bevy_mod_picking#101]
Not sure if you were planning on releasing along side the next bevy release but the changes in master that register systems as `PreUpdate` instead of `PostUpdate` seem pretty useful. I was about to file a bug/open a PR for this and noticed it was already fixed.

**Comment by aevyrie** [comment]
> Not sure if you were planning on releasing along side the next bevy release but the changes in master that register systems as `PreUpdate` instead of `PostUpdate` seem pretty useful. I was about to file a bug/open a PR for this and noticed it was already fixed.

Due to the extra overhead, I don't backport changes from master to the last bevy release. I generally release to crates.io within a few days of a Bevy release. With the intended Bevy release cadence of 2ish months, the delay between releases is generally not too large.

If it's a blocking issue for you, I'm always happy to help along PRs!

**Comment by robo-corg** [comment]
Understandable and thank you for making bevy_mod_picking! I back ported the PreUpdate change to a branch https://github.com/robo-corg/bevy_mod_picking/tree/am/pre-update-0.4.0 and should keep me going until bevy 0.6. Not sure its worth merging back to this repo unless you want to setup branches for serial releases like `v0.4.x`.
