### ISSUE TITLE
Sprite sheet bundle picking support

### ISSUE THREAD

**Issue by Twyker** [aevyrie/bevy_mod_picking#210]
Analogues to the sprite bundle picking support - which seems to work fine now - is there any support planned for the SpriteSheetBundle as well or should this even be working already?

What's the best way to go about this otherwise? Just add a MaterialMesh2DBundle as a child to the Entity with the SpriteSheetBundle?

**Comment by focustense** [comment]
I just whipped up a working `TextureAtlasSpriteBackend` using an implementation that's identical to `SpriteBackend` except with the following changes in the `filter_map`:

```rs
        let position = sprite_transform.translation();
        let scale = sprite_transform.compute_transform().scale;
        let half_extents = sprite
            .custom_size
            .or_else(|| {
                let texture_atlas = texture_atlases.get(handle)?;
                let texture_bounds = texture_atlas.textures.get(sprite.index)?;
                Some(texture_bounds.size())
            })
            .map(|size| size / 2.0 * scale.truncate())?;
```

Declaration changes include:

```rs
    texture_atlases: Res<Assets<TextureAtlas>>,
    sprites: Query<(
        Entity,
        &Handle<TextureAtlas>,
        &TextureAtlasSprite,
        &GlobalTransform,
        &ComputedVisibility,
        Option<&FocusPolicy>,
    )>,
```

(most likely, the `SpriteBackend` should be taking into account `scale` as well).

There's no other change; the only practical difference between a `Sprite` and a `TextureAtlasSprite` here is that the latter's bounds are taken from a `TextureAtlas` and not an `Image`.

**Comment by aevyrie** [comment]
I'm happy to include this in the sprite picking backend if you PR it!

**Comment by focustense** [comment]
I can do that, although what I was posted is kind of ugly copypasta. Do you have a design preference out of the following?

- Add a new `TextureAtlasSpriteBackend` that's nearly identical to `SpriteBackend` except for the changes above
- Update the `SpriteBackend` to also handle `TextureAtlasSprite`, i.e. by making some of the query elements `Option` and checking them all in the `half_extents` calculation
- Write a "2D backend" generic system using a trait to compute the bounds or do a bounds check, since that seems to be the only thing that varies?

I used the picking mod for another [example](https://github.com/focustense/mina/blob/main/examples/bevy_app/src/arrow_button.rs#L123) I did with the nascent vector shapes addon, and it's kind of the same story; it's circular, so there's no "bounding box", but the "bounds check" is trivial and everything else is pretty much the same. Not sure how common this is beyond the two sprite types and my toy example, though, and I don't want to overcomplicate things.

**Comment by bonsairobo** [comment]
> Update the SpriteBackend to also handle TextureAtlasSprite, i.e. by making some of the query elements Option and checking them all in the half_extents calculation

This option seems the most straightforward while avoiding code duplication. Writing a generic system seems like more effort with unclear benefit.

**Comment by aevyrie** [comment]
This is now supported and can be tested in the sprite example.
https://github.com/aevyrie/bevy_mod_picking/blob/8f78621a6c03b73c0b896dc65af8b151d5e01bcc/examples/sprite.rs#L133

https://github.com/aevyrie/bevy_mod_picking/assets/2632925/4027227b-07fc-4708-8fda-19bf86fb633a
